language: go
go:
  - 1.14.x
  - master
sudo: false
install: true
env:
  - GO111MODULE=on
script:
  - pip install iso8601 requests securesystemslib==0.14.2 six tuf
  - go test -race ./...

notifications:
  email:
    on_success: never
    on_failure: always
